{
 "title": "K8S Dashboard",
 "description": "【English version】2025.01.25 Updates，kubernetesComprehensive display of resources！Includes K8S Overall Resource Overview、Microservices Resource Details、Pod Resource Details andK8SNetwork Bandwidth，Optimization metrics。https://grafana.com/orgs/starsliao/dashboards",
 "tags": [
  "Prometheus",
  "Kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "tenant_id", "label": "Tenant ID" },
   {
    "name": "origin_prometheus",
    "label": "K8S",
    "query": {
     "query": "label_values(kube_node_info{tenant_id=~\"$tenant_id\"},origin_prometheus)"
    }
   },
   {
    "name": "Node",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info{tenant_id=~\"$tenant_id\",origin_prometheus=~\"$origin_prometheus\"},node)"
    }
   },
   {
    "name": "NameSpace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{tenant_id=~\"$tenant_id\",origin_prometheus=~\"$origin_prometheus\"},namespace)"
    }
   },
   {
    "name": "Container",
    "label": "Microservice (Container Name)",
    "query": {
     "query": "label_values(kube_pod_container_info{tenant_id=~\"$tenant_id\",origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\"},container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{tenant_id=~\"$tenant_id\",origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\",container=~\"$Container\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Resource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Memory Ratio",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",container!=\"\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}) / sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"}) / sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Memory Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"}) / sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Memory Limit Rate"
    }
   ]
  },
  {
   "title": "Node CPU Ratio",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",container!=\"\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}[2m])) / sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "CPU Utilization Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"}) / sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "CPU Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"}) / sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "CPU Limit Rate"
    }
   ]
  },
  {
   "title": "Nodes with Pod",
   "type": "bargauge",
   "description": "Number of cluster nodes，Nodes POD Number of，NodesPODUpper Limit",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Number of nodes"
    },
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$origin_prometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Pod Number of nodes"
    },
    {
     "expr": "sum(kube_node_status_allocatable{origin_prometheus=~\"$origin_prometheus\",resource=\"pods\", unit=\"integer\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Upper limit Pod"
    }
   ]
  },
  {
   "title": "Namespace Resource Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (namespace) (count by (namespace, pod) (kube_pod_info{origin_prometheus=~\"$origin_prometheus\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\", node!=\"\"} and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))))"
    },
    {
     "expr": "count(kube_service_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}) by(namespace)"
    },
    {
     "expr": "count by (namespace)({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\",origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_configmap_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "$NameSpace：Network Overview（Associable nodes and namespaces）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{cluster_id=~\"$origin_prometheus\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}[2m]))*8",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{cluster_id=~\"$origin_prometheus\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}[2m]))*8",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Node Memory Information",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",container!=\"\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Node CPU Number of cores",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",id=\"/\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}[2m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Node Storage Information",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{cluster_id=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}) / sum(max by (node) (label_replace(container_fs_limit_bytes{cluster_id=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}, \"node\", \"$1\", \"k8s_node_name\", \"(.+)\")))",
     "legendFormat": "Utilization Rate"
    },
    {
     "expr": "sum(container_fs_usage_bytes{cluster_id=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(max by (node) (label_replace(container_fs_limit_bytes{cluster_id=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}, \"node\", \"$1\", \"k8s_node_name\", \"(.+)\")))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_metadata_generation{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}) + count(kube_daemonset_metadata_generation{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}) + count(kube_statefulset_metadata_generation{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Workload"
    },
    {
     "expr": "count(count by (namespace, pod) (kube_pod_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\", node!=\"\"} and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))))",
     "legendFormat": "Total Pod"
    },
    {
     "expr": "count by(key,cluster_id)(kube_node_spec_taint{origin_prometheus=~\"$origin_prometheus\",key=~\"node.kubernetes.io.*\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "count by(cluster_id)(kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "count by(cluster_id)(kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}) - count by(cluster_id)(kube_node_spec_taint{origin_prometheus=~\"$origin_prometheus\",key!~\"node.kubernetes.io.*\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Normal Node"
    },
    {
     "expr": "count by(key,cluster_id)(kube_node_spec_taint{origin_prometheus=~\"$origin_prometheus\",key!~\"node.kubernetes.io.*\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Memory Usage【$Node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",container!=\"\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "CPU Used Cores【$Node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{origin_prometheus=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"}[2m]))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Pod Number and nodes【$Node】",
   "type": "timeseries",
   "description": "Number of Cluster Nodes，Nodes POD Number of，Nodes POD Upper Limit",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Number of nodes"
    },
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$origin_prometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Pod Number"
    },
    {
     "expr": "sum(kube_node_status_allocatable{origin_prometheus=~\"$origin_prometheus\",resource=\"pods\", unit=\"integer\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "Upper Limit Pod"
    }
   ]
  },
  {
   "title": "$Node：Nodes CPU Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (k8s_node_name) (irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",container!=\"\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}[2m]))) / (sum by (k8s_node_name) (label_replace(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"}, \"k8s_node_name\", \"$1\", \"node\", \"(.+)\"))) * 100",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "$Node：Node Memory Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (k8s_node_name) (container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",container!=\"\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"})) / (sum by (k8s_node_name) (label_replace(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"}, \"k8s_node_name\", \"$1\", \"node\", \"(.+)\"))) * 100",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "$Node：Node Network Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by (k8s_node_name) (irate(container_network_receive_bytes_total{cluster_id=~\"$origin_prometheus\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}[2m]))*8",
     "legendFormat": "Inflow:{{k8s_node_name}}"
    },
    {
     "expr": "sum by (k8s_node_name) (irate(container_network_transmit_bytes_total{cluster_id=~\"$origin_prometheus\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}[2m]))*8",
     "legendFormat": "Outflows:{{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "$Node：Node Information Detail",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster_id=~\"$origin_prometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\",node!=\"\", tenant_id=~\"$tenant_id\"}) by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))",
     "legendFormat": "pod Number"
    },
    {
     "expr": "sum(label_replace(irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",container!=\"\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}[2m]), \"node\", \"$1\", \"k8s_node_name\", \"(.+)\")) by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))"
    },
    {
     "expr": "kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"} - 0 and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\",node!=\"\", tenant_id=~\"$tenant_id\"}) by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\",node!=\"\", tenant_id=~\"$tenant_id\"}) by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))"
    },
    {
     "expr": "sum(label_replace(container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",container!=\"\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}, \"node\", \"$1\", \"k8s_node_name\", \"(.+)\")) by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"}) by (node) - 0 and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\",node!=\"\", tenant_id=~\"$tenant_id\"}) by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\",node!=\"\", tenant_id=~\"$tenant_id\"}) by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))"
    },
    {
     "expr": "sum by (node) ( sum by (nodename) ( sum by (instance, nodename) ( max by (instance, device, nodename) ( (node_filesystem_size_bytes{tenant_id=~\"$tenant_id\", fstype!~\"tmpfs|squashfs|fuse[.]snapfuse|overlay|aufs|efivarfs\", mountpoint=~\"^/$|^/boot/efi$|^/mnt/data.*$\"} - node_filesystem_avail_bytes{tenant_id=~\"$tenant_id\", fstype!~\"tmpfs|squashfs|fuse[.]snapfuse|overlay|aufs|efivarfs\", mountpoint=~\"^/$|^/boot/efi$|^/mnt/data.*$\"}) * on(instance) group_left(nodename) node_uname_info{tenant_id=~\"$tenant_id\"} ) ) ) * on(nodename) group_left(node) ( max by (nodename, node) ( label_replace(( kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\", node=~\"^$Node$\"} or kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\", node=~\"^$Node$\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", node=~\"^$Node$\"} or kube_node_info{origin_prometheus=~\"$origin_prometheus\", node=~\"^$Node$\"} ), \"nodename\", \"$1\", \"node\", \"(.*)\") ) ) )"
    },
    {
     "expr": "sum by (node) ( sum by (nodename) ( sum by (instance, nodename) ( max by (instance, device, nodename) ( node_filesystem_size_bytes{tenant_id=~\"$tenant_id\", fstype!~\"tmpfs|squashfs|fuse[.]snapfuse|overlay|aufs|efivarfs\", mountpoint=~\"^/$|^/boot/efi$|^/mnt/data.*$\"} * on(instance) group_left(nodename) node_uname_info{tenant_id=~\"$tenant_id\"} ) ) ) * on(nodename) group_left(node) ( max by (nodename, node) ( label_replace(( kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\", node=~\"^$Node$\"} or kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\", node=~\"^$Node$\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", node=~\"^$Node$\"} or kube_node_info{origin_prometheus=~\"$origin_prometheus\", node=~\"^$Node$\"} ), \"nodename\", \"$1\", \"node\", \"(.*)\") ) ) )"
    },
    {
     "expr": "(sum(label_replace(container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",container!=\"\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}, \"node\", \"$1\", \"k8s_node_name\", \"(.+)\")) by (node)) / (sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"}) by (node)) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))",
     "legendFormat": "Memory Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\",node!=\"\", tenant_id=~\"$tenant_id\"})by (node) / sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))",
     "legendFormat": "Memory Requests%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\",node!=\"\", tenant_id=~\"$tenant_id\"})by (node) / sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))",
     "legendFormat": "Memory Limit%"
    },
    {
     "expr": "(sum(label_replace(irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",container!=\"\",k8s_node_name=~\"^$Node$\", tenant_id=~\"$tenant_id\"}[2m]), \"node\", \"$1\", \"k8s_node_name\", \"(.+)\")) by (node)) / (sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"}) by (node)) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))",
     "legendFormat": "CPU Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\",node!=\"\", tenant_id=~\"$tenant_id\"})by (node) / sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))",
     "legendFormat": "CPU Requests%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\",node!=\"\", tenant_id=~\"$tenant_id\"})by (node) / sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))",
     "legendFormat": "Memory Limit%"
    },
    {
     "expr": "(sum by (node) ( sum by (nodename) ( sum by (instance, nodename) ( max by (instance, device, nodename) ( (node_filesystem_size_bytes{tenant_id=~\"$tenant_id\", fstype!~\"tmpfs|squashfs|fuse[.]snapfuse|overlay|aufs|efivarfs\", mountpoint=~\"^/$|^/boot/efi$|^/mnt/data.*$\"} - node_filesystem_avail_bytes{tenant_id=~\"$tenant_id\", fstype!~\"tmpfs|squashfs|fuse[.]snapfuse|overlay|aufs|efivarfs\", mountpoint=~\"^/$|^/boot/efi$|^/mnt/data.*$\"}) * on(instance) group_left(nodename) node_uname_info{tenant_id=~\"$tenant_id\"} ) ) ) * on(nodename) group_left(node) ( max by (nodename, node) ( label_replace(( kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\", node=~\"^$Node$\"} or kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\", node=~\"^$Node$\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", node=~\"^$Node$\"} or kube_node_info{origin_prometheus=~\"$origin_prometheus\", node=~\"^$Node$\"} ), \"nodename\", \"$1\", \"node\", \"(.*)\") ) ) )) / (sum by (node) ( sum by (nodename) ( sum by (instance, nodename) ( max by (instance, device, nodename) ( node_filesystem_size_bytes{tenant_id=~\"$tenant_id\", fstype!~\"tmpfs|squashfs|fuse[.]snapfuse|overlay|aufs|efivarfs\", mountpoint=~\"^/$|^/boot/efi$|^/mnt/data.*$\"} * on(instance) group_left(nodename) node_uname_info{tenant_id=~\"$tenant_id\"} ) ) ) * on(nodename) group_left(node) ( max by (nodename, node) ( label_replace(( kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\", node=~\"^$Node$\"} or kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\", node=~\"^$Node$\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", node=~\"^$Node$\"} or kube_node_info{origin_prometheus=~\"$origin_prometheus\", node=~\"^$Node$\"} ), \"nodename\", \"$1\", \"node\", \"(.*)\") ) ) ))",
     "legendFormat": "Disk Usage%"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster_id=~\"$origin_prometheus\",resource=\"pods\", unit=\"integer\",node=~\"^$Node$\", tenant_id=~\"$tenant_id\"})by (node) and on(node) (count by (node) (kube_node_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"} or kube_node_info{cluster_id=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))",
     "legendFormat": "PodCaps"
    }
   ]
  },
  {
   "title": "PVC Storage Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
    },
    {
     "expr": "min by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}) + max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}) /(min by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}) + max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"}))*100",
     "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
    },
    {
     "expr": "count by (namespace,persistentvolumeclaim)(kube_pod_spec_volumes_persistentvolumeclaims_info{origin_prometheus=~\"$origin_prometheus\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces CPU Usage kernel(>0.005 cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",container !=\"\",container!=\"POD\", tenant_id=~\"$tenant_id\"}[2m])) by (namespace) > 0.005",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Namespaces WSS Memory Usage (>100MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",container !=\"\",container!=\"POD\", tenant_id=~\"$tenant_id\"}) by (namespace) > 100*1024*1024",
     "legendFormat": "{{namespace} {{ pod }}"
    }
   ]
  },
  { "title": "Pod Resource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "$Node：Pod Resource Detail(Associable Nodes)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}[2m])) by (container, pod,node,namespace) / (sum(container_spec_cpu_quota{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}/100000) by (container, pod,node,namespace)) "
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}[2m])) by (container, pod,node,namespace)",
     "legendFormat": "CPUKernel Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod,node,namespace)",
     "legendFormat": "wss%"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod,node,namespace)",
     "legendFormat": "wss"
    },
    {
     "expr": "sum (container_memory_rss{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod,node,namespace)",
     "legendFormat": "rss%"
    },
    {
     "expr": "sum (container_memory_rss{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod,node,namespace)",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"} * on (pod) group_left(node) kube_pod_info{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",node=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}"
    },
    {
     "expr": "time() - kube_pod_created{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"} * on(pod) group_right kube_pod_container_info{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",namespace=~\"$NameSpace\",container =~\"$Container\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_fs_limit_bytes{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",pod!=\"\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum by (namespace, pod) (rate(container_network_receive_bytes_total{cluster_id=~\"$origin_prometheus\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\"$Pod\",pod!=\"\", tenant_id=~\"$tenant_id\"}[2m])) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, pod) (rate(container_network_transmit_bytes_total{cluster_id=~\"$origin_prometheus\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\"$Pod\",pod!=\"\", tenant_id=~\"$tenant_id\"}[2m])) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Containers CPU Utilization (Maximum100%Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}[2m])) by (container, pod) / (max(container_spec_cpu_quota{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}/100000) by (container, pod)) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Container Memory Usage (Associatable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod)/ max(container_spec_memory_limit_bytes{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod) * 100",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max (container_memory_rss{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod)/ max(container_spec_memory_limit_bytes{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod) * 100",
     "legendFormat": "RSS：{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Network bandwidth per second (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (rate(container_network_receive_bytes_total{cluster_id=~\"$origin_prometheus\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\"$Pod\", tenant_id=~\"$tenant_id\"}[2m])) * 8",
     "legendFormat": "Inflow:{{ pod}}"
    },
    {
     "expr": "sum by (namespace, pod) (rate(container_network_transmit_bytes_total{cluster_id=~\"$origin_prometheus\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\"$Pod\", tenant_id=~\"$tenant_id\"}[2m])) * 8",
     "legendFormat": "Outflow:{{ pod}}"
    }
   ]
  },
  {
   "title": "Pod Containers CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}[2m])) by (container, pod,node,namespace)",
     "legendFormat": "CPU Usage：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "Pod CPU Limitations：{{ container}}"
    }
   ]
  },
  {
   "title": "Pod Containers WSS Memory Usage (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod,node,namespace)",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "PodMemory Limits：{{ container}}"
    }
   ]
  },
  {
   "title": "Pod Containers RSS Memory Usage (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_rss{cluster_id=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container, pod,k8s_node_name,namespace)",
     "legendFormat": "RSS：{{ pod }}"
    }
   ]
  },
  {
   "title": "Microservices (Container Name) Resource Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Microservices (Container Name) Resource Statistics",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}[2m])) by (container) / (sum(container_spec_cpu_quota{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}/100000) by (container))"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}[2m])) by (container)",
       "legendFormat": "Total Cores Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)/ sum(container_spec_memory_limit_bytes{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_rss{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)/ sum(container_spec_memory_limit_bytes{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)",
       "legendFormat": "Average Memory%(RSS)"
      },
      {
       "expr": "sum (container_memory_rss{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)",
       "legendFormat": "Total Memory Usage (RSS) "
      },
      {
       "expr": "sum by(container) (kube_pod_container_resource_requests{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"})"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster_id=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)"
      },
      {
       "expr": "avg(container_fs_usage_bytes{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)"
      },
      {
       "expr": "count(kube_pod_container_info{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by(container,namespace)"
      },
      {
       "expr": "avg(container_fs_limit_bytes{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)"
      }
     ]
    },
    {
     "title": "Microservices (Container Name) Average CPU Usage (Maximum100%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}[2m])) by (container) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}/100000) by (container)) * 100",
       "legendFormat": "{{ container}}"
      }
     ]
    },
    {
     "title": "Microservice (Container Name) Average Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container) * 100",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container) * 100",
       "legendFormat": "RSS：{{ container }}"
      }
     ]
    },
    {
     "title": "Microservice (Container Name) Network bandwidth per second (Associable Nodes)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum by (container) (rate(container_network_receive_bytes_total{cluster_id=~\"$origin_prometheus\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\",container=~\"$Container\", tenant_id=~\"$tenant_id\"}[2m])) * 8",
       "legendFormat": "Inflow:{{ container }}"
      },
      {
       "expr": "sum by (container) (rate(container_network_transmit_bytes_total{cluster_id=~\"$origin_prometheus\",k8s_node_name=~\"^$Node$\",namespace=~\"$NameSpace\",container=~\"$Container\", tenant_id=~\"$tenant_id\"}[2m])) * 8",
       "legendFormat": "Outflow:{{ container }}"
      }
     ]
    },
    {
     "title": "Microservices (Container Name) Overall CPU Cores Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)",
       "legendFormat": "CPU Limitations：{{ container}}"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}[2m])) by (container)",
       "legendFormat": "CPU Core Usage：{{ container}}"
      }
     ]
    },
    {
     "title": "Microservices (Container Name) Overall Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)",
       "legendFormat": "Memory Limit：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by (container)",
       "legendFormat": "RSS：{{ container }}"
      }
     ]
    },
    {
     "title": "Microservice (Container Name) Pod Number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_pod_container_info{cluster_id=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\", tenant_id=~\"$tenant_id\"}) by(container,namespace)",
       "legendFormat": "{{namespace}}：{{ container }}"
      }
     ]
    }
   ]
  }
 ]
}