{
 "title": "Kubernetes / Views / Nodes",
 "description": "This is a modern 'Nodes View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "tenant_id", "label": "Tenant ID" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info{tenant_id=~\"$tenant_id\",cluster_id!=\"\",cluster_id!=\"cluster\"}, cluster_id)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{tenant_id=~\"$tenant_id\",cluster_id=~\"$cluster\"}, node)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{tenant_id=~\"$tenant_id\",nodename=\"$node\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU  Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"} - node_memory_MemAvailable_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"}) / sum(node_memory_MemTotal_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"})"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (namespace, pod) (kube_pod_info{node=\"$node\", cluster_id=~\"$cluster\", tenant_id=~\"$tenant_id\"}))"
    }
   ]
  },
  {
   "title": "List of pods on node ($node)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$node\", cluster_id=~\"$cluster\", tenant_id=~\"$tenant_id\"}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=\"$node\", resource=\"cpu\", unit=\"core\", tenant_id=~\"$tenant_id\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"} - node_memory_MemAvailable_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=\"$node\", resource=\"memory\", unit=\"byte\", tenant_id=~\"$tenant_id\"})"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_time_seconds{instance=\"$instance\", tenant_id=~\"$tenant_id\"} - node_boot_time_seconds{instance=\"$instance\", tenant_id=~\"$tenant_id\"})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (mode) (rate(node_cpu_seconds_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]) * 100)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"} - node_memory_MemFree_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"} - (node_memory_Cached_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"} + node_memory_Buffers_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "RAM Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"} - node_memory_SwapFree_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "SWAP Total"
    }
   ]
  },
  {
   "title": "CPU usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (sum by (namespace, pod) (rate(container_cpu_usage_seconds_total{image!=\"\", tenant_id=~\"$tenant_id\"}[$__rate_interval])) * on(namespace, pod) group_left() max by (namespace, pod) (kube_pod_info{node=\"$node\", cluster_id=~\"$cluster\", tenant_id=~\"$tenant_id\"}))",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (sum by (namespace, pod) (container_memory_working_set_bytes{image!=\"\", tenant_id=~\"$tenant_id\"}) * on(namespace, pod) group_left() max by (namespace, pod) (kube_pod_info{node=\"$node\", cluster_id=~\"$cluster\", tenant_id=~\"$tenant_id\"}))",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of CPU Core Throttled",
   "type": "timeseries",
   "description": "Number of times a CPU core has been throttled on an instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_core_throttles_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "Nb of cpu core throttles"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Context Switches & Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "rate(node_intr_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "node_filefd_allocated{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "Allocated file descriptors"
    }
   ]
  },
  {
   "title": "Time Sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "Estimated error in seconds"
    },
    {
     "expr": "node_timex_maxerror_seconds{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "Maximum error in seconds"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Network usage (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_errs_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_errs_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network usage (packet/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_packets_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network total drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_drop_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "TCP Currently Established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "TCP Currently Established"
    }
   ]
  },
  {
   "title": "NF Conntrack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "NF Conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=\"$instance\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "NF Conntrack limit"
    }
   ]
  },
  { "title": "Kubernetes Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Persistent Volumes - Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes{node=\"$node\", tenant_id=~\"$tenant_id\"} * on(node) group_left() max by (node) (kube_node_info{cluster_id=~\"$cluster\", node=\"$node\", tenant_id=~\"$tenant_id\"})) / max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{node=\"$node\", tenant_id=~\"$tenant_id\"} * on(node) group_left() max by (node) (kube_node_info{cluster_id=~\"$cluster\", node=\"$node\", tenant_id=~\"$tenant_id\"}))) or (max by (namespace, persistentvolumeclaim) (label_replace(kubelet_volume_stats_used_bytes{tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\") * on(nodeip) group_left() label_replace(node_uname_info{nodename=\"$node\", tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\")) / max by (namespace, persistentvolumeclaim) (label_replace(kubelet_volume_stats_capacity_bytes{tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\") * on(nodeip) group_left() label_replace(node_uname_info{nodename=\"$node\", tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\")))",
     "legendFormat": "{{ namespace }} - {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Usage in GB",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes{node=\"$node\", tenant_id=~\"$tenant_id\"} * on(node) group_left() max by (node) (kube_node_info{cluster_id=~\"$cluster\", node=\"$node\", tenant_id=~\"$tenant_id\"}))) or (max by (namespace, persistentvolumeclaim) (label_replace(kubelet_volume_stats_used_bytes{tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\") * on(nodeip) group_left() label_replace(node_uname_info{nodename=\"$node\", tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\")))"
    },
    {
     "expr": "(max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{node=\"$node\", tenant_id=~\"$tenant_id\"} * on(node) group_left() max by (node) (kube_node_info{cluster_id=~\"$cluster\", node=\"$node\", tenant_id=~\"$tenant_id\"}))) or (max by (namespace, persistentvolumeclaim) (label_replace(kubelet_volume_stats_capacity_bytes{tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\") * on(nodeip) group_left() label_replace(node_uname_info{nodename=\"$node\", tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\")))"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_inodes_used{node=\"$node\", tenant_id=~\"$tenant_id\"} * on(node) group_left() max by (node) (kube_node_info{cluster_id=~\"$cluster\", node=\"$node\", tenant_id=~\"$tenant_id\"})) / sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_inodes{node=\"$node\", tenant_id=~\"$tenant_id\"} * on(node) group_left() max by (node) (kube_node_info{cluster_id=~\"$cluster\", node=\"$node\", tenant_id=~\"$tenant_id\"}))) * 100) or ((sum by (namespace, persistentvolumeclaim) (label_replace(kubelet_volume_stats_inodes_used{tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\") * on(nodeip) group_left() label_replace(node_uname_info{nodename=\"$node\", tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\")) / sum by (namespace, persistentvolumeclaim) (label_replace(kubelet_volume_stats_inodes{tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\") * on(nodeip) group_left() label_replace(node_uname_info{nodename=\"$node\", tenant_id=~\"$tenant_id\"}, \"nodeip\", \"$1\", \"instance\", \"^([^:]+):\"))) * 100)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  { "title": "Node Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "FS usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "FS inode usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_files_free{instance=\"$instance\", tenant_id=~\"$tenant_id\"} / node_filesystem_files{instance=\"$instance\", tenant_id=~\"$tenant_id\"} * 100)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Reads by disk (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Writes by disk (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Completed reads by disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "read/s" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Completed writes by disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "write/s" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk(s) io/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "io/s" } },
   "targets": [
    {
     "expr": "sum by (device) (rate(node_disk_reads_completed_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]) + rate(node_disk_writes_completed_total{instance=\"$instance\", tenant_id=~\"$tenant_id\"}[$__rate_interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "FS - Device Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (mountpoint) (node_filesystem_device_error{instance=\"$instance\", tenant_id=~\"$tenant_id\"})",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  }
 ]
}