{
 "title": "LLM Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "tenant_id", "label": "Tenant ID" },
   {
    "name": "model_name",
    "label": "Model Name",
    "query": {
     "query": "label_values(request_prompt_tokens_sum{tenant_id=~\"$tenant_id\"}, model_name)"
    }
   },
   {
    "name": "model_id",
    "label": "Model ID",
    "query": {
     "query": "label_values(request_prompt_tokens_sum{tenant_id=~\"$tenant_id\",model_name=~\"$model_name\"}, model_id)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(request_prompt_tokens_sum{tenant_id=~\"$tenant_id\",model_name=~\"$model_name\", model_id=~\"$model_id\"}, cluster_id)"
    }
   },
   { "name": "interval", "label": "Interval" }
  ]
 },
 "panels": [
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "description": "Latency from request start to first token returned (in seconds).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(model_name) (rate(e2e_request_latency_seconds_sum{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval]))\n/\nsum by(model_name) (rate(e2e_request_latency_seconds_count{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_name) (rate(e2e_request_latency_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_name) (rate(e2e_request_latency_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_name) (rate(e2e_request_latency_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_name) (rate(e2e_request_latency_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gpu_cache_usage_perc{\r\n  model_name=~\"$model_name\",\r\n  model_id=~\"$model_id\",\r\n  cluster_id=~\"$cluster_id\",\r\n tenant_id=~\"$tenant_id\"}",
     "legendFormat": "GPU Cache Usage"
    },
    {
     "expr": "cpu_cache_usage_perc{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}",
     "legendFormat": "CPU Cache Usage"
    }
   ]
  },
  {
   "title": "Input token rate",
   "type": "timeseries",
   "description": "Number of prompt tokens processed per second",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "tokens/s" } },
   "targets": [
    {
     "expr": "sum by (model_name) (rate(request_prompt_tokens_sum{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval]))",
     "legendFormat": "Prompt Tokens/Sec"
    }
   ]
  },
  {
   "title": "Output token rate",
   "type": "timeseries",
   "description": "Number of output tokens generated per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "tokens/s" } },
   "targets": [
    {
     "expr": "sum by (model_name) (rate(generation_tokens_total{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval]))",
     "legendFormat": "Generation Tokens/Sec"
    }
   ]
  },
  {
   "title": "Time To First Token Latency",
   "type": "timeseries",
   "description": "P50, P90, P95, and P99 TTFT latency.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by(model_name) (rate(time_to_first_token_seconds_sum{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval]))\n/\nsum by(model_name) (rate(time_to_first_token_seconds_count{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_name)(rate(time_to_first_token_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_name)(rate(time_to_first_token_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_name) (rate(time_to_first_token_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_name)(rate(time_to_first_token_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Time Per Output Token Latency",
   "type": "timeseries",
   "description": "Time per output token latency.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_name) (rate(time_per_output_token_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_name) (rate(time_per_output_token_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_name) (rate(time_per_output_token_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_name) (rate(time_per_output_token_seconds_bucket{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "(sum by(model_name) (rate(time_per_output_token_seconds_sum{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval]))\n/\nsum by(model_name) (rate(time_per_output_token_seconds_count{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])))",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Prefix Cache Hit Rate",
   "type": "timeseries",
   "description": "Percentage of prefix cache queries that resulted in a cache hit (GPU).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(gpu_prefix_cache_hits_total{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval]) / increase(gpu_prefix_cache_queries_total{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval])",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "Requests Prefill and Decode Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(model_name, model_id) (rate(request_decode_time_seconds_sum{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval]))",
     "legendFormat": "Decode"
    },
    {
     "expr": "sum by(model_name, model_id) (rate(request_prefill_time_seconds_sum{model_name=~\"$model_name\", model_id=~\"$model_id\", cluster_id=~\"$cluster_id\", tenant_id=~\"$tenant_id\"}[$interval]))",
     "legendFormat": "Prefill"
    }
   ]
  }
 ]
}