{
 "title": "Switch dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": {
     "query": "label_values(node_cpu_seconds_total,exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(exported_instance) (\n  (\n\tnode_memory_MemTotal_bytes{job=\"opentelemetry-collector\", exported_instance=~\"$Host\"} \n\t- \n\tnode_memory_MemAvailable_bytes{job=\"opentelemetry-collector\", exported_instance=~\"$Host\"}\n  )\n  / \n  node_memory_MemTotal_bytes{job=\"opentelemetry-collector\", exported_instance=~\"$Host\"}\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSU state",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(exported_instance) (\n  nvswitch_platform_environment_psu_state{job=\"opentelemetry-collector\", exported_instance=\"$Host\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FAN Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(exported_instance) (nvswitch_platform_environment_fan_cur_speed{exported_instance=\"$Host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n  100 - (avg by(exported_instance) (\n\trate(node_cpu_seconds_total{mode=\"idle\", exported_instance=\"$Host\"}[5m])\n  ) * 100), 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FAN state",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(exported_instance) (\n  nvswitch_platform_environment_fan_state{exported_instance=\"$Host\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(exported_instance) (\n  avg_over_time(nvswitch_platform_environment_temp_current{exported_instance=\"$Host\"}[5m])\n)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(exported_instance) (\n  rate(node_disk_io_time_seconds_total{exported_instance=\"$Host\"}[1h])\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvswitch_interface_proto_down{job=\"opentelemetry-collector\",exported_instance=\"$Host\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvswitch_interface_mtu_bytes{job=\"opentelemetry-collector\", exported_instance=\"$Host\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  }
 ]
}